import 'package:account_atlas/core/storage/app_database.dart';
import 'package:account_atlas/features/accounts/data/dtos/account_local_dto.dart';
import 'package:account_atlas/features/services/data/dtos/plan_local_dto.dart';
import 'package:account_atlas/features/services/data/dtos/service_local_dto.dart';
import 'package:sqflite/sqflite.dart';

class MockDataSeeder {
  static Future<void> seedIfEmpty() async {
    final db = await AppDatabase.instance.database;
    final accountCount =
        Sqflite.firstIntValue(
          await db.rawQuery('SELECT COUNT(*) FROM accounts'),
        ) ??
        0;
    final serviceCount =
        Sqflite.firstIntValue(
          await db.rawQuery('SELECT COUNT(*) FROM account_services'),
        ) ??
        0;

    if (accountCount > 0 || serviceCount > 0) {
      return;
    }

    final now = DateTime.now();
    final accounts = [
      AccountLocalDto(
        identifier: 'coremagic@gmail.com',
        provider: 'gmail',
        createdAt: now
            .subtract(const Duration(days: 12))
            .millisecondsSinceEpoch,
      ),
      AccountLocalDto(
        identifier: 'nyamnyang@gmail.com',
        provider: 'facebook',
        createdAt: now.subtract(const Duration(days: 9)).millisecondsSinceEpoch,
      ),
      AccountLocalDto(
        identifier: 'smalltide@naver.com',
        provider: 'naver',
        createdAt: now.subtract(const Duration(days: 7)).millisecondsSinceEpoch,
      ),
      AccountLocalDto(
        identifier: 'sosmayday@outlook.com',
        provider: 'apple',
        createdAt: now.subtract(const Duration(days: 5)).millisecondsSinceEpoch,
      ),
      AccountLocalDto(
        identifier: 'power2000@naver.com',
        provider: 'github',
        createdAt: now.subtract(const Duration(days: 2)).millisecondsSinceEpoch,
      ),
    ];

    const servicesPerAccount = 9;
    var serviceIndex = 0;

    for (final account in accounts) {
      final accountId = await db.insert('accounts', account.toInsertMap());
      await _insertServicesForAccount(
        db: db,
        accountId: accountId,
        baseTime: now,
        startIndex: serviceIndex,
        count: servicesPerAccount,
      );
      serviceIndex += servicesPerAccount;
    }
  }

  static Future<void> _insertServicesForAccount({
    required Database db,
    required int accountId,
    required DateTime baseTime,
    required int startIndex,
    required int count,
  }) async {
    for (var index = 0; index < count; index += 1) {
      final template =
          _serviceTemplates[(startIndex + index) % _serviceTemplates.length];
      final createdAt = baseTime
          .subtract(Duration(days: 1 + index))
          .millisecondsSinceEpoch;

      final serviceId = await db.insert(
        'account_services',
        ServiceLocalDto(
          accountId: accountId,
          providedServiceKey: template.providedServiceKey,
          displayName: template.displayName,
          loginType: template.loginType,
          loginId: template.loginId,
          category: template.category,
          isPay: template.isPay,
          memo: template.memo,
          createdAt: createdAt,
        ).toInsertMap(),
      );

      if (template.isPay == 1) {
        final billingCycle = template.billingCycle ?? 0;
        final nextBillingDate = billingCycle == 1
            ? baseTime.add(const Duration(days: 365)).millisecondsSinceEpoch
            : baseTime.add(const Duration(days: 30)).millisecondsSinceEpoch;
        await db.insert(
          'plans',
          PlanLocalDto(
            accountServiceId: serviceId,
            currency: template.currency ?? 'USD',
            amount: template.amount ?? 0,
            billingCycle: billingCycle,
            nextBillingDate: nextBillingDate,
            createdAt: createdAt,
          ).toInsertMap(),
        );
      }
    }
  }
}

class _MockService {
  final String providedServiceKey;
  final String displayName;
  final String loginType;
  final String? loginId;
  final String category;
  final int isPay;
  final String? memo;
  final int? amount;
  final int? billingCycle;
  final String? currency;

  const _MockService({
    required this.providedServiceKey,
    required this.displayName,
    required this.loginType,
    required this.loginId,
    required this.category,
    required this.isPay,
    this.memo,
    this.amount,
    this.billingCycle,
    this.currency,
  });
}

final List<_MockService> _serviceTemplates = [
  _MockService(
    providedServiceKey: 'netflix',
    displayName: 'Netflix',
    loginType: 'email',
    loginId: 'user@netflix.com',
    category: 'video',
    isPay: 1,
    memo: 'Premium',
    amount: 2299,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'youtube_premium',
    displayName: 'YouTube Premium',
    loginType: 'email',
    loginId: 'user@gmail.com',
    category: 'video',
    isPay: 1,
    memo: 'Individual',
    amount: 1399,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'disney_plus',
    displayName: 'Disney+',
    loginType: 'email',
    loginId: 'user@disney.com',
    category: 'video',
    isPay: 1,
    memo: 'Basic (Ads)',
    amount: 799,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'max',
    displayName: 'Max',
    loginType: 'email',
    loginId: 'user@max.com',
    category: 'video',
    isPay: 1,
    memo: 'Ad-Free',
    amount: 1699,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'prime_video',
    displayName: 'Amazon Prime Video',
    loginType: 'email',
    loginId: 'user@amazon.com',
    category: 'video',
    isPay: 1,
    memo: 'Video Only',
    amount: 899,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'spotify',
    displayName: 'Spotify',
    loginType: 'email',
    loginId: 'user@spotify.com',
    category: 'music',
    isPay: 1,
    memo: 'Individual',
    amount: 1199,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'apple_music',
    displayName: 'Apple Music',
    loginType: 'email',
    loginId: 'user@icloud.com',
    category: 'music',
    isPay: 1,
    memo: 'Family',
    amount: 1699,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'youtube_music',
    displayName: 'YouTube Music',
    loginType: 'email',
    loginId: 'user@gmail.com',
    category: 'music',
    isPay: 1,
    memo: 'Premium',
    amount: 1099,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'amazon_music',
    displayName: 'Amazon Music',
    loginType: 'email',
    loginId: 'user@amazon.com',
    category: 'music',
    isPay: 1,
    memo: 'Unlimited',
    amount: 1099,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'tidal',
    displayName: 'Tidal',
    loginType: 'email',
    loginId: 'user@tidal.com',
    category: 'music',
    isPay: 1,
    memo: 'Individual',
    amount: 1099,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'amazon_prime',
    displayName: 'Amazon Prime',
    loginType: 'email',
    loginId: 'user@amazon.com',
    category: 'shopping',
    isPay: 1,
    memo: 'Monthly',
    amount: 1499,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'walmart_plus',
    displayName: 'Walmart+',
    loginType: 'email',
    loginId: 'user@walmart.com',
    category: 'shopping',
    isPay: 1,
    memo: 'Monthly',
    amount: 1295,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'uber_one',
    displayName: 'Uber One',
    loginType: 'email',
    loginId: 'user@uber.com',
    category: 'shopping',
    isPay: 1,
    memo: 'Monthly',
    amount: 999,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'doordash',
    displayName: 'DoorDash',
    loginType: 'email',
    loginId: 'user@doordash.com',
    category: 'shopping',
    isPay: 1,
    memo: 'DashPass',
    amount: 999,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'instacart_plus',
    displayName: 'Instacart+',
    loginType: 'email',
    loginId: 'user@instacart.com',
    category: 'shopping',
    isPay: 1,
    memo: 'Monthly',
    amount: 999,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'costco',
    displayName: 'Costco',
    loginType: 'email',
    loginId: 'user@costco.com',
    category: 'shopping',
    isPay: 1,
    memo: 'Gold Star',
    amount: 6500,
    billingCycle: 1,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'microsoft_365',
    displayName: 'Microsoft 365',
    loginType: 'email',
    loginId: 'user@outlook.com',
    category: 'tool',
    isPay: 1,
    memo: 'Personal',
    amount: 699,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'google_one',
    displayName: 'Google One',
    loginType: 'email',
    loginId: 'user@gmail.com',
    category: 'tool',
    isPay: 1,
    memo: 'Basic (100GB)',
    amount: 199,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'notion',
    displayName: 'Notion',
    loginType: 'email',
    loginId: 'user@notion.so',
    category: 'tool',
    isPay: 1,
    memo: 'Plus',
    amount: 1000,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'adobe_cc',
    displayName: 'Adobe Creative Cloud',
    loginType: 'email',
    loginId: 'user@adobe.com',
    category: 'tool',
    isPay: 1,
    memo: 'All Apps',
    amount: 5999,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'dropbox',
    displayName: 'Dropbox',
    loginType: 'email',
    loginId: 'user@dropbox.com',
    category: 'tool',
    isPay: 1,
    memo: 'Plus',
    amount: 1199,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'x',
    displayName: 'X',
    loginType: 'social',
    loginId: null,
    category: 'sns',
    isPay: 1,
    memo: 'Premium',
    amount: 800,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'linkedin',
    displayName: 'LinkedIn',
    loginType: 'email',
    loginId: 'user@linkedin.com',
    category: 'sns',
    isPay: 1,
    memo: 'Premium Career',
    amount: 3999,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'discord',
    displayName: 'Discord',
    loginType: 'social',
    loginId: null,
    category: 'sns',
    isPay: 1,
    memo: 'Nitro',
    amount: 999,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'snapchat',
    displayName: 'Snapchat',
    loginType: 'social',
    loginId: null,
    category: 'sns',
    isPay: 1,
    memo: 'Snapchat+',
    amount: 399,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'telegram',
    displayName: 'Telegram',
    loginType: 'social',
    loginId: null,
    category: 'sns',
    isPay: 1,
    memo: 'Premium',
    amount: 499,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'chatgpt',
    displayName: 'ChatGPT',
    loginType: 'email',
    loginId: 'user@openai.com',
    category: 'ai',
    isPay: 1,
    memo: 'Plus',
    amount: 2000,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'claude',
    displayName: 'Claude',
    loginType: 'email',
    loginId: 'user@anthropic.com',
    category: 'ai',
    isPay: 1,
    memo: 'Pro',
    amount: 2000,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'perplexity',
    displayName: 'Perplexity',
    loginType: 'email',
    loginId: 'user@perplexity.ai',
    category: 'ai',
    isPay: 1,
    memo: 'Pro',
    amount: 2000,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'github_copilot',
    displayName: 'GitHub Copilot',
    loginType: 'email',
    loginId: 'user@github.com',
    category: 'ai',
    isPay: 1,
    memo: 'Individual',
    amount: 1000,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'midjourney',
    displayName: 'Midjourney',
    loginType: 'email',
    loginId: 'user@midjourney.com',
    category: 'ai',
    isPay: 1,
    memo: 'Basic',
    amount: 1000,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'xbox_game_pass',
    displayName: 'Xbox Game Pass',
    loginType: 'email',
    loginId: 'user@xbox.com',
    category: 'game',
    isPay: 1,
    memo: 'Ultimate',
    amount: 1999,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'playstation_plus',
    displayName: 'PlayStation Plus',
    loginType: 'email',
    loginId: 'user@playstation.com',
    category: 'game',
    isPay: 1,
    memo: 'Extra',
    amount: 1499,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'nintendo_online',
    displayName: 'Nintendo Switch Online',
    loginType: 'email',
    loginId: 'user@nintendo.com',
    category: 'game',
    isPay: 1,
    memo: 'Individual',
    amount: 399,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'geforce_now',
    displayName: 'GeForce Now',
    loginType: 'email',
    loginId: 'user@nvidia.com',
    category: 'game',
    isPay: 1,
    memo: 'Priority',
    amount: 999,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'ea_play',
    displayName: 'EA Play',
    loginType: 'email',
    loginId: 'user@ea.com',
    category: 'game',
    isPay: 1,
    memo: 'Monthly',
    amount: 599,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'duolingo',
    displayName: 'Duolingo',
    loginType: 'email',
    loginId: 'user@duolingo.com',
    category: 'education',
    isPay: 1,
    memo: 'Super',
    amount: 1299,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'coursera',
    displayName: 'Coursera',
    loginType: 'email',
    loginId: 'user@coursera.org',
    category: 'education',
    isPay: 1,
    memo: 'Coursera Plus',
    amount: 5900,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'masterclass',
    displayName: 'MasterClass',
    loginType: 'email',
    loginId: 'user@masterclass.com',
    category: 'education',
    isPay: 1,
    memo: 'Individual',
    amount: 1500,
    billingCycle: 1,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'skillshare',
    displayName: 'Skillshare',
    loginType: 'email',
    loginId: 'user@skillshare.com',
    category: 'education',
    isPay: 1,
    memo: 'Premium',
    amount: 1375,
    billingCycle: 1,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'grammarly',
    displayName: 'Grammarly',
    loginType: 'email',
    loginId: 'user@grammarly.com',
    category: 'education',
    isPay: 1,
    memo: 'Premium',
    amount: 1200,
    billingCycle: 1,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'tinder',
    displayName: 'Tinder',
    loginType: 'email',
    loginId: 'user@tinder.com',
    category: 'others',
    isPay: 1,
    memo: 'Gold',
    amount: 2499,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'strava',
    displayName: 'Strava',
    loginType: 'email',
    loginId: 'user@strava.com',
    category: 'others',
    isPay: 1,
    memo: 'Premium',
    amount: 1199,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'nordvpn',
    displayName: 'NordVPN',
    loginType: 'email',
    loginId: 'user@nordvpn.com',
    category: 'others',
    isPay: 1,
    memo: 'Standard',
    amount: 1299,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'calm',
    displayName: 'Calm',
    loginType: 'email',
    loginId: 'user@calm.com',
    category: 'others',
    isPay: 1,
    memo: 'Premium',
    amount: 1499,
    billingCycle: 0,
    currency: 'USD',
  ),
  _MockService(
    providedServiceKey: 'nyt',
    displayName: 'The New York Times',
    loginType: 'email',
    loginId: 'user@nytimes.com',
    category: 'others',
    isPay: 1,
    memo: 'All Access',
    amount: 2500,
    billingCycle: 0,
    currency: 'USD',
  ),
];
